# Generated by Django 4.1 on 2024-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='icone',
            field=models.CharField(choices=[('lni-package', 'Caixa'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], default='lni-package', max_length=20, verbose_name='Icone'),
        ),
    ]
