# Generated by Django 4.1 on 2024-08-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='estrela',
            field=models.IntegerField(default=0, verbose_name='Estrelas'),
        ),
    ]
