# Generated by Django 4.1 on 2024-08-08 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_avaliacao_estrela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estrela',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Estrelas'),
        ),
    ]
